[project]
name = "srm-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.31.0",
    "PyQt6>=6.5.0",
    "PyMySQL>=1.1.0",
    "pyinstaller>=6.16.0",
    "gdown>=5.2.0",
]
